// Code generated by Slice Machine. DO NOT EDIT.

import Boeken from "./Boeken/index.svelte";
import Members from "./Members/index.svelte";

export const components = {
  boeken: Boeken,
  members: Members,
};
